"""Synchronize install and lock requirements from pyproject.toml."""

from __future__ import annotations

import argparse
import platform
import subprocess
import sys
import tomllib
from collections.abc import Sequence
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


class RequirementsSyncError(RuntimeError):
    """Raised when dependency files cannot be synchronized safely."""


DEPENDENCY_GROUPS = (
    ("Application runtime", None),
    ("OpenHands repository-agent runtime", "agent"),
    ("Authorized local knowledge retrieval", "knowledge"),
    ("Verification and dependency maintenance", "dev"),
)


def _dependency_groups(pyproject_text: str) -> list[tuple[str, list[str]]]:
    document = tomllib.loads(pyproject_text)
    project = document.get("project", {})
    optional = project.get("optional-dependencies", {})
    groups: list[tuple[str, list[str]]] = []
    for label, extra in DEPENDENCY_GROUPS:
        dependencies = project.get("dependencies", []) if extra is None else optional.get(extra, [])
        if not isinstance(dependencies, list) or not all(
            isinstance(item, str) for item in dependencies
        ):
            source = (
                "project.dependencies"
                if extra is None
                else f"project.optional-dependencies.{extra}"
            )
            raise RequirementsSyncError(f"{source} must be a list of requirement strings")
        groups.append((label, dependencies))
    return groups


def _locked_versions(lock_text: str) -> dict[str, str]:
    versions: dict[str, str] = {}
    for raw_line in lock_text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or raw_line[:1].isspace():
            continue
        try:
            requirement = Requirement(line)
        except ValueError:
            continue
        exact = [
            specifier.version
            for specifier in requirement.specifier
            if specifier.operator == "==" and "*" not in specifier.version
        ]
        if len(exact) == 1:
            versions[canonicalize_name(requirement.name)] = exact[0]
    return versions


def _pinned_requirement(source: str, versions: dict[str, str]) -> str:
    requirement = Requirement(source)
    canonical_name = canonicalize_name(requirement.name)
    version = versions.get(canonical_name)
    if version is None:
        raise RequirementsSyncError(
            f"Direct dependency {requirement.name} is missing from requirements.lock"
        )
    if requirement.url:
        raise RequirementsSyncError(
            f"Direct URL dependency {requirement.name} cannot be pinned from requirements.lock"
        )
    if requirement.specifier and not requirement.specifier.contains(version, prereleases=True):
        raise RequirementsSyncError(
            f"Locked {requirement.name} version {version} violates {requirement.specifier}"
        )
    extras = f"[{','.join(sorted(requirement.extras))}]" if requirement.extras else ""
    marker = f"; {requirement.marker}" if requirement.marker else ""
    return f"{requirement.name}{extras}=={version}{marker}"


def render_direct_requirements(pyproject_text: str, lock_text: str) -> str:
    """Render pinned direct dependencies using versions from the full lock."""

    versions = _locked_versions(lock_text)
    lines = [
        "# This file is autogenerated from pyproject.toml and requirements.lock.",
        "# Refresh it on Linux with Python 3.13:",
        "#",
        "#    .venv/bin/python scripts/sync_requirements.py",
    ]
    seen: set[str] = set()
    for label, dependencies in _dependency_groups(pyproject_text):
        rendered: list[str] = []
        for source in dependencies:
            name = canonicalize_name(Requirement(source).name)
            if name in seen:
                continue
            seen.add(name)
            rendered.append(_pinned_requirement(source, versions))
        if rendered:
            lines.extend(("", f"# {label}", *rendered))
    return "\n".join(lines) + "\n"


def check_direct_requirements(
    pyproject_path: Path,
    lock_path: Path,
    direct_path: Path,
) -> None:
    """Fail when requirements.txt differs from its canonical generated form."""

    expected = render_direct_requirements(pyproject_path.read_text(), lock_path.read_text())
    actual = direct_path.read_text() if direct_path.exists() else ""
    if actual != expected:
        raise RequirementsSyncError(
            "requirements.txt is out of date; run scripts/sync_requirements.py "
            "on Linux with Python 3.13"
        )


def ensure_refresh_platform(system: str, version: Sequence[int]) -> None:
    """Protect the canonical lock from host-dependent resolution."""

    if system != "Linux":
        raise RequirementsSyncError("Full dependency refresh must run on Linux")
    if tuple(version[:2]) != (3, 13):
        raise RequirementsSyncError("Full dependency refresh requires Python 3.13")


def refresh_requirements(root: Path) -> None:
    """Regenerate the full lock, then derive the direct installer file."""

    ensure_refresh_platform(platform.system(), tuple(sys.version_info[:2]))
    pyproject_path = root / "pyproject.toml"
    lock_path = root / "requirements.lock"
    direct_path = root / "requirements.txt"
    command = [
        sys.executable,
        "-m",
        "piptools",
        "compile",
        "--extra=agent",
        "--extra=knowledge",
        "--extra=dev",
        "--strip-extras",
        f"--output-file={lock_path}",
        str(pyproject_path),
    ]
    subprocess.run(command, cwd=root, check=True)
    direct_path.write_text(
        render_direct_requirements(pyproject_path.read_text(), lock_path.read_text())
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify requirements.txt against pyproject.toml and requirements.lock",
    )
    arguments = parser.parse_args(argv)
    root = Path(__file__).resolve().parents[2]
    try:
        if arguments.check:
            check_direct_requirements(
                root / "pyproject.toml",
                root / "requirements.lock",
                root / "requirements.txt",
            )
            print("requirements.txt is synchronized")
        else:
            refresh_requirements(root)
            print("requirements.lock and requirements.txt refreshed")
    except (OSError, RequirementsSyncError, subprocess.CalledProcessError) as error:
        print(f"requirements sync failed: {error}", file=sys.stderr)
        return 1
    return 0
