// Generated by NovAtom TCAD Agent Sentaurus compiler 0.1.0.
// Input is a validated portable specification. Do not edit this file.
Electrode {
  { Name="anode" Voltage=0 WorkFunction=4.1 }
  { Name="cathode" Voltage=0 WorkFunction=4.1 }
}

File {
  Grid="device.tdr"
  Plot="sdevice.tdr"
  Current="sdevice.plt"
  Output="sdevice.log"
}

Physics {
  Temperature=300
  Fermi
  Mobility
  Recombination( SRH Auger )
  EffectiveIntrinsicDensity( OldSlotboom )
}

Plot {
  Potential
  ElectricField/Vector
  eDensity
  hDensity
  SpaceCharge
  ConductionBandEnergy
  ValenceBandEnergy
  eQuasiFermiEnergy
  hQuasiFermiEnergy
  eCurrent/Vector
  hCurrent/Vector
  eMobility
  hMobility
  TotalRecombination
}

Math {
  Extrapolate
  RelErrControl
  Digits=5
  Iterations=50
}

Solve {
  Coupled { Poisson Electron Hole }
}
